AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.13
    CodeUri: .
    Environment:
      Variables:
        ENV: local

Resources:
  ProtectedRoutesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.protected_routes_handler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /protected/{proxy+}
            Method: ANY

  UnprotectedRoutesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.unprotected_routes_handler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /unprotected/{proxy+}
            Method: ANY
            Auth:
              Authorizer: NONE
            Cors:
              AllowMethods: "'GET,POST,DELETE,PATCH'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
              AllowCredentials: "'*'"