AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.13
    CodeUri: .
    Environment:
      Variables:
        STAGE: local

Resources:
  Users:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /users
            Method: GET
