AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: python3.13
    CodeUri: .
    Timeout: 30
    Environment:
      Variables:
        ENV: local

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyLambdaTokenAuthorizer
        Authorizers:
          MyLambdaTokenAuthorizer:
            FunctionArn: !GetAtt LambdaAuthorizer.Arn

  ProtectedRoutesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.protected_routes_handler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /protected/{proxy+}
            Method: ANY
            Cors:
              AllowMethods: "'GET,POST,DELETE,PATCH'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
              AllowCredentials: "'*'"

  UnprotectedRoutesLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.unprotected_routes_handler
      Events:
        ApiGatewayEvent:
          Type: Api
          Properties:
            Path: /unprotected/{proxy+}
            Method: ANY
            Auth:
              Authorizer: NONE
            Cors:
              AllowMethods: "'GET,POST,DELETE,PATCH'"
              AllowHeaders: "'*'"
              AllowOrigin: "'*'"
              AllowCredentials: "'*'"
  
  MigrationTool:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.utils.migration.lambda_handler
  
  LambdaAuthorizer:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src.utils.authorizer.lambda_handler