version: "3.8"
services:
  frontend:
    container_name: store-ui
    build: ./frontend
    command: npm run dev
    environment:
      - NODE_ENV=local
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000

  api:
    container_name: store-api
    command: gunicorn --bind :8080 --workers 1 --reload app:app 
    build: ./backend
    environment:
      - ENV=local
      - PYTHONUNBUFFERED=TRUE
    volumes:
      - ./backend:/var/task
    ports:
      - 8080:8080

  dynamodb:
    container_name: store-db
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    ports:
      - "8000:8000"
