version: "3.8"
services: 
  frontend:
    container_name: frontend
    build: ./frontend
    command: npm run dev
    environment:
      - NODE_ENV=development 
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
      - 2999:2999
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -inMemory"
    image: "amazon/dynamodb-local:latest"
    container_name: dyanmodb
    ports:
      - "8000:8000"