version: "3.8"
services: 
  frontend:
    container_name: frontend
    build: ./frontend
    command: npm run dev
    environment:
      - NODE_ENV=development 
    volumes:
      - ./frontend:/app
    ports:
      - 3000:3000
